language: c
compiler:
 - gcc
 - clang
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq automake autoconf libtool make zlib1g-dev python
script:
 - libtoolize --copy --force --install
 - aclocal
 - autoheader
 - autoconf
 - automake -a -c -f --foreign
 - ./configure --disable-silent-rules
 - make -j4
